import type { CoverLetter } from "@/lib/api";

/**
 * The letter this application will send, before it sends it.
 *
 * The worker has written `review_json["cover_letter"]` since the wiring
 * landed, and nothing rendered it — so a document addressed to an employer,
 * generated by a model, was attached to an application the owner approved
 * without ever being able to read it. That is the same failure the untailored
 * résumé had: the pipeline does the work, the approval screen does not show
 * it, and nothing notices because no test asserts what the screen displays.
 *
 * A refusal is rendered too. A letter has no original to fall back to, so the
 * alternative to a bad one is none — and the owner deciding whether to write
 * one by hand needs "the guard refused it, here is why" to look different from
 * "the form never asked".
 */
export function CoverLetterView({ letter }: { letter: CoverLetter }) {
  const model = letter.answered_by;

  if (!letter.accepted) {
    return (
      <div className="space-y-2">
        <p className="text-sm text-attn">
          No letter is attached. {letter.rejected_reason ?? "The fabrication guard refused it."}
        </p>
        <p className="font-mono text-xs text-ink-faint">
          Nothing false was sent. Write one by hand if this posting needs it.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-3">
      <p className="font-mono text-xs text-ink-soft">
        {letter.word_count ?? 0} words
        {letter.sentences_dropped ? (
          <span className="text-attn">
            {" "}
            · {letter.sentences_dropped} sentence{letter.sentences_dropped === 1 ? "" : "s"} dropped
            by the guard
          </span>
        ) : null}
        {letter.reused ? <span className="text-ink-faint"> · reused, nothing sent</span> : null}
      </p>

      <p className="font-mono text-xs text-ink-faint">
        written by{" "}
        {model ? (
          <span className="text-ink-soft">{model}</span>
        ) : (
          <span className="italic">not recorded</span>
        )}
      </p>

      {letter.text ? (
        // Plain text in a <p>, never innerHTML: this string came from a model
        // and is about to be read as a document, not rendered as markup.
        <p className="whitespace-pre-wrap border border-rule bg-paper px-4 py-3 text-sm leading-relaxed">
          {letter.text}
        </p>
      ) : (
        <p className="text-sm text-ink-soft">
          The letter was stored but its text is not in this record, so it cannot be shown here.
        </p>
      )}
    </div>
  );
}
