"""company source status and discovery state

The backfill is the part worth reading. `source_status` defaults to
`unverified`, which would label all 105 live registry boards as unconfirmed and
make the dashboard wrong in the opposite direction from the problem this column
exists to fix.

So it is backfilled **from evidence already in the row**, and never from an
assumption:

- a company with a slug, an ATS and a `last_polled_at` has demonstrably had its
  board answer, so it becomes `verified`, and the evidence says it was a
  backfill rather than a check performed today;
- a company with a careers URL that has never been polled stays `unverified` —
  we have a candidate and no answer from it;
- a company with neither a careers URL nor a domain becomes `no_website`, since
  there is nothing discovery could even attempt.

`verified` here means "this board answered us", not "we confirmed it is the
right company" — ownership verification is a separate check that did not exist
when these rows were written, and claiming it retroactively is exactly the kind
of unearned confidence the column is meant to prevent. The evidence field says
which of the two it is.

Revision ID: 53964fd524ac
Revises: 43f6690f44a6
Create Date: 2026-09-12 22:30:26.201694

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "53964fd524ac"
down_revision: str | Sequence[str] | None = "43f6690f44a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "source_status",
            sa.String(length=20),
            server_default=sa.text("'unverified'"),
            nullable=False,
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "source_evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "companies", sa.Column("source_verified_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("companies", sa.Column("discovery_failure", sa.Text(), nullable=True))
    op.add_column("companies", sa.Column("supplied_website", sa.Text(), nullable=True))
    op.add_column("companies", sa.Column("supplied_career_url", sa.Text(), nullable=True))
    op.add_column("companies", sa.Column("source_file", sa.Text(), nullable=True))
    op.add_column("companies", sa.Column("source_row", sa.Integer(), nullable=True))
    op.create_index("ix_companies_source_status", "companies", ["source_status"], unique=False)
    op.create_check_constraint(
        "ck_companies_source_status",
        "companies",
        "source_status IN ('no_website', 'hint', 'unverified', 'verified', 'failed')",
    )
    op.add_column(
        "company_crawl_states",
        sa.Column("discovery_next_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "company_crawl_states",
        sa.Column("discovery_last_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "company_crawl_states",
        sa.Column("discovery_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.create_index(
        "ix_company_crawl_states_discovery_next_at",
        "company_crawl_states",
        ["discovery_next_at"],
        unique=False,
    )

    # Boards that have answered us. `last_polled_at` is only ever written
    # after a successful fetch, so it is evidence rather than intent.
    op.execute("""
        UPDATE companies
           SET source_status = 'verified',
               source_verified_at = last_polled_at,
               source_evidence = jsonb_build_object(
                   'method', 'backfill_board_answered',
                   'ats', ats_type,
                   'slug', slug,
                   'last_polled_at', to_jsonb(last_polled_at),
                   'note', 'the board answered before this column existed; '
                           'company ownership was never separately confirmed'
               )
         WHERE slug IS NOT NULL
           AND ats_type IS NOT NULL
           AND last_polled_at IS NOT NULL
    """)

    # Nothing to try. Separated from "tried and failed" because the fix is
    # finding a URL, not crawling better.
    op.execute("""
        UPDATE companies
           SET source_status = 'no_website',
               source_evidence = jsonb_build_object('method', 'backfill_no_url')
         WHERE careers_url IS NULL AND domain IS NULL AND source_status = 'unverified'
    """)

    # Discovery has never run for any existing row, so every company that is
    # not already verified is due for it immediately. NULL reads as "as soon as
    # possible", the same convention `next_due_at` uses.
    op.execute("""
        INSERT INTO company_crawl_states (company_id, discovery_next_at)
        SELECT id, NULL FROM companies
        ON CONFLICT (company_id) DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_company_crawl_states_discovery_next_at", table_name="company_crawl_states")
    op.drop_column("company_crawl_states", "discovery_attempts")
    op.drop_column("company_crawl_states", "discovery_last_at")
    op.drop_column("company_crawl_states", "discovery_next_at")
    op.drop_constraint("ck_companies_source_status", "companies", type_="check")
    op.drop_index("ix_companies_source_status", table_name="companies")
    op.drop_column("companies", "source_row")
    op.drop_column("companies", "source_file")
    op.drop_column("companies", "supplied_career_url")
    op.drop_column("companies", "supplied_website")
    op.drop_column("companies", "discovery_failure")
    op.drop_column("companies", "source_verified_at")
    op.drop_column("companies", "source_evidence")
    op.drop_column("companies", "source_status")
    # ### end Alembic commands ###
