"""crawl run and per-company crawl state

Revision ID: 9bda42579189
Revises: c33a361f9611
Create Date: 2026-09-12 11:05:08.483958

Every existing company gets a state row here rather than on first crawl. The
alternative — create it lazily — makes the scheduler's query a LEFT JOIN with
a NULL branch, and that branch would be the one covering the entire registry
until each company happened to be polled once. Backfilling means the index on
`next_due_at` is useful from the first tick.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9bda42579189"
down_revision: str | Sequence[str] | None = "c33a361f9611"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("companies_total", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("companies_fetched", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("companies_skipped", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("companies_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("postings_new", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("postings_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("postings_closed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "suspect_companies",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'aborted')", name="ck_crawl_runs_status"
        ),
        sa.CheckConstraint(
            "trigger IN ('scheduled', 'manual', 'forced')", name="ck_crawl_runs_trigger"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_crawl_runs_started_at",
        "crawl_runs",
        [sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "company_crawl_states",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_status", sa.String(length=20), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_run_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["last_run_id"], ["crawl_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", name="uq_company_crawl_states_company"),
    )
    op.create_index(
        "ix_company_crawl_states_next_due_at", "company_crawl_states", ["next_due_at"], unique=False
    )

    # `next_due_at` is `is_due`'s arithmetic, materialized: a company polled
    # at T with a 3600s interval is next due at T+3600. A company never polled
    # gets NULL, which the scheduler reads as "as soon as possible" — the same
    # answer `is_due` gives for a NULL `last_polled_at`.
    op.execute("""
        INSERT INTO company_crawl_states (company_id, last_attempt_at, last_success_at, next_due_at)
        SELECT id,
               last_polled_at,
               last_polled_at,
               last_polled_at + make_interval(secs => poll_interval_s)
          FROM companies
        ON CONFLICT (company_id) DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_company_crawl_states_next_due_at", table_name="company_crawl_states")
    op.drop_table("company_crawl_states")
    op.drop_index("ix_crawl_runs_started_at", table_name="crawl_runs")
    op.drop_table("crawl_runs")
    # ### end Alembic commands ###
