"""add company board hash

Revision ID: f31201519b23
Revises: d8e8e09d2523
Create Date: 2026-08-15 23:23:49.449466

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f31201519b23"
down_revision: str | Sequence[str] | None = "d8e8e09d2523"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("board_hash", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "board_hash")
    # ### end Alembic commands ###
